server:
  port: 8083
spring:
  application:
    name: cloud-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8080/eureka/      #服务注册中心地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-provider
